version: '3.8'

services:
  auth:
    container_name: auth
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules # isolate container's node_modules from local node_modules (different OS versions)
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: postgres_auth
    image: postgres:13.1
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes: #isolate DB data from potentially different OS
  data:
